name: PR Workflows

# Run action on pull request event
on: [pull_request]


jobs:
  # Build exampleSite
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v4.1.1

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install node modules
      run: npm install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3.0.0
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: |
        hugo --minify

  # Check for any broken links
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # checkout to latest commit
    - uses: actions/checkout@master

    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v2.0.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        args: "--verbose --exclude-mail ${{steps.preview.outputs.url}} --exclude=['https://www.udemy.com/']"
        output: lychee/out.md

    - name: Comment Broken Links
      if: ${{ steps.lychee.outputs.exit_code != 0 }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: lychee/out.md

    - name: Fail workflow if broken links found
      if: ${{ steps.lychee.outputs.exit_code != 0 }}
      run: exit 1
